---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Reset all UFW rules
  community.general.ufw:
    state: reset
  when: reset

- name: Deny all incoming traffic by default
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Allow SSH access
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Rate-limit SSH connections to mitigate brute-force attacks
  community.general.ufw:
    rule: limit
    port: '22'
    proto: tcp

- name: Allow HTTP traffic
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: http

- name: Allow HTTPS traffic
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
  when: https

- name: Allow all traffic on wt0 interface
  community.general.ufw:
    direction: in
    interface: wt0
    rule: allow

- name: Allow TCP to FNE port
  community.general.ufw:
    rule: allow
    port: "{{ hostvars[inventory_hostname]['fne_port'] }}"
    proto: tcp
  when: open_fne_port

- name: Allow UDP to FNE port
  community.general.ufw:
    rule: allow
    port: "{{ hostvars[inventory_hostname]['fne_port'] }}"
    proto: udp
  when: open_fne_port

- name: Enable UFW
  community.general.ufw:
    state: enabled
    default: deny
